language: go
go:
  - tip
  - 1.x
  - 1.8.x
  - 1.7.x
  - 1.6.x

sudo: false

before_install:
  - go get -u golang.org/x/lint/golint
  - mkdir -p $GOPATH/src/github.com/vbatts && ln -sf $(pwd) $GOPATH/src/github.com/vbatts/git-validation && go get ./...

before_script:
  - env

install: true

script:
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go build .
  - go test -v ./...
  - ./git-validation -run DCO,short-subject,dangling-whitespace -v
